#!/usr/bin/env bash
# shellcheck disable=SC2154
set -euEo pipefail

readonly BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$BASE_PATH"

[[ ! -f ./.env ]] && cp --verbose ./.env{.template,}
[[ ! -f ./dist/.env ]] && cp --verbose ./dist/.env{.template,}

set -o allexport
. ./.env
set +o allexport


# Install
sudo apt-get update -y
sudo apt-get install -y wget git apt-cacher-ng
wget -qO - "${iscript}/docker/docker-ubuntu" | bash

readonly apt_proxy_ip="$(ifconfig docker0 | awk 'NR==2 {print $2}')"

cat <<EOF >> ./.env
# APT
APT_PROXY='Acquire::http::Proxy "http://${apt_proxy_ip}:3142/";'
EOF
